### ISSUE TITLE
Error: Cannot find module 'express-rate-limit'

### ISSUE THREAD

**Issue by mkphaber** [TheComputerGenie/KMD-solo-mining#13]
Error: Cannot find module 'express-rate-limit'
Require stack:
- /home/pools/KMD-solo-mining/lib/workers/website.js
- /home/pools/KMD-solo-mining/init.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
    at Module._load (node:internal/modules/cjs/loader:984:27)
    at Module.require (node:internal/modules/cjs/loader:1234:19)
    at require (node:internal/modules/helpers:176:18)
    at new module.exports (/home/pools/KMD-solo-mining/lib/workers/website.js:15:18)
    at Object.<anonymous> (/home/pools/KMD-solo-mining/init.js:28:4)
    at Module._compile (node:internal/modules/cjs/loader:1375:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1434:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pools/KMD-solo-mining/lib/workers/website.js',
    '/home/pools/KMD-solo-mining/init.js'
  ]
}

**Comment by aldomex78** [comment]
Got the same error
