### ISSUE TITLE
nothing works and description unclear

### ISSUE THREAD

**Issue by Arn0m** [TheComputerGenie/KMD-solo-mining#53]
`CLI: CLI listening on port 17117
[12:39:43 09/14] [Website]	Example app listening at http://0.0.0.0:8088
[12:39:43 09/14] [Init]	Spawned proxy on 1 threads(s)
[12:39:43 09/14] [Stratum]	Could not start pool, error with init batch RPC call: {"type":"offline","message":"connect ECONNREFUSED 127.0.0.1:7771"}
/root/KMD-solo-mining/lib/workers/website.js:29
                blocks = result[0].response.blocks;
                                            ^

TypeError: Cannot read properties of undefined (reading 'blocks')
    at /root/KMD-solo-mining/lib/workers/website.js:29:45
    at /root/KMD-solo-mining/lib/stratum/daemon.js:131:17
    at wrapper (/root/KMD-solo-mining/node_modules/async/dist/async.js:272:20)
    at iteratorCallback (/root/KMD-solo-mining/node_modules/async/dist/async.js:502:17)
    at /root/KMD-solo-mining/node_modules/async/dist/async.js:328:20
    at itemFinished (/root/KMD-solo-mining/lib/stratum/daemon.js:123:17)
    at /root/KMD-solo-mining/lib/stratum/daemon.js:128:88
    at ClientRequest.<anonymous> (/root/KMD-solo-mining/lib/stratum/daemon.js:78:17)
    at ClientRequest.emit (node:events:519:28)
    at Socket.socketErrorListener (node:_http_client:500:9)

Node.js v21.7.3
[12:40:13 09/14] [Website]	Website process died, spawning replacement...
[12:40:15 09/14] [Website]	Example app listening at http://0.0.0.0:8088
`

Thats a lot of errors for a fresh installtions!

**Comment by Arn0m** [comment]
Settings also unclear ... Wallet ID or BTC Address ....

**Comment by TheComputerGenie** [comment]
a) This isn't meant for novices, but I will try to walk you through any bits time allows me to.
> Yes, this is "a lot" for beginners to understand; however, solo mining isn't meant to be easy.

b) **Never** use root as a normal user
c) "offline" means offline - your daemon is not accepting connections on port 7771 (either it's not running or your config is wrong)
d) See [config readme](https://github.com/TheComputerGenie/KMD-solo-mining/blob/master/config.md)
e) What would make you think a BTC address would be valid for solo-mining KMD?
